INSERT INTO Difficulty (name, subtier, sort) VALUES
    ('Tier 0', 'high', 19),
    ('Tier 0', 'mid', 18),
    ('Tier 0', 'low', 17),
    ('Tier 1', 'high', 16),
    ('Tier 1', 'mid', 15),
    ('Tier 1', 'low', 14),
    ('Tier 2', 'high', 13),
    ('Tier 2', 'mid', 12),
    ('Tier 2', 'low', 11),
    ('Tier 3', 'high', 10),
    ('Tier 3', 'mid', 9),
    ('Tier 3', 'low', 8),
    ('Tier 3', 'guard', 7),
    ('Tier 4', NULL, 6),
    ('Tier 5', NULL, 5),
    ('Tier 6', NULL, 4),
    ('Tier 7', NULL, 3),
    ('Standard', NULL, 2),
    ('Undetermined', NULL, 1);
